#!/usr/bin/env bash
# ravencito shower-thought — Random shower thoughts from Dave

cmd_shower_thought() {
    local thoughts=(
        "What person would I become if I took responsibility for shaping myself?"
        "Whose approval am I auditioning for?"
        "Use AI to move faster, not to be absent. Show your intent, assumptions, and recommendation or it's just a button press. I don't need help pressing buttons; I need your judgment."
        "Kindness is strength under control. Cruelty is weakness or strength without control. Indifference is control without a soul."
        "What have you taught yourself in the last six months that nobody required you to learn?"
        "Arguing with me is pointless, I know I was wrong 5 minutes ago. Now I am just trying to make you mad."
        "Has English effectively become the primary abstraction layer for software in the AI era?"
        "Love is the only thing that gets more valuable when it's repeatedly given away."
        "Focus on improving not proving."
        "Always be a little earlier, kinder, and smarter than is necessary."
        "When code gets cheaper to produce, organizations don't reduce the amount of builds; they raise their sights and do even more."
        "How do I know if I'm being patient (a skill) or stubborn (a flaw)?"
        "Spend time with the bitter and become bitter, spend time with the best and become better."
        "Imagine having such weak conviction in your beliefs that you are open to persuasion and debate."
        "A job that keeps you mentally sharp is a blessing."
        "I am not what happened to me, I am what I choose to become."
        "The most underrated skill in engineering: showing up when you don't feel like it."
        "Thinking about thinking improves thinking."
        "Like it or not, you are always leading by example. Every action, every word and every silence is an example. Be the kind of leader you would follow."
        "Leaders don't want praise, they want progress."
        "Leaders don't want more followers, they want more leaders."
        "The best engineers tolerate uncomfortable truths, change and uncertainty but have little patience for bullshit, mediocrity and clowns."
        "People tend to forget that engineers are human. Often, these people are the engineers themselves."
        "Errors are normal human behavior. Design systems that minimize their consequences."
        "Stop asking who dropped the ball and start asking why are they juggling."
        "Three unhelpful phrases: We have always done it that way. This is just who I am. I do not have the time."
        "I have never finished a social media session and felt better about myself or future. I have never gone for an adventure in the outdoors and felt bad about myself or the future."
        "New engineers have a lot to learn, old engineers have a lot to unlearn."
        "The magic you are looking for is in the work you are avoiding."
        "If you can solve difficult engineering challenges, you can solve the problem of eating well and regular exercise for a lifetime of health."
        "You cannot build confidence by avoiding embarrassment."
        "You did not have to cause it to correct it. It is not your fault, but it is your project."
        "Your response to a mistake, not the mistake itself, is what you will be judged for."
        "Some days you can't win. Some days you can't lose. Everyday you can't quit."
        "Learn with intensity, respond to emergencies calmly."
        "Don't wait until you are promoted to start acting like a leader."
        "Being enthusiastic is worth 25 IQ points."
        "Teach others what you should have been taught."
        "Whatever scares you, go train on it."
        "The lights are not always on you. Other people do not notice your flaws as much as you think they do. They are too busy judging their own imperfections to notice yours."
        "Every challenge is you versus you."
        "Always be yourself. A company full of clones is boring."
        "Most of my mentors do not know I exist. Think of how many people you could be mentoring unknowingly."
        "Do not expect a new team member or inexperienced clients to have the knowledge it took you years to acquire."
        "Everything that needs to be said has already been said. But since no one was listening, everything must be said again."
        "The main thing is to keep the main thing the main thing."
        "Wisdom is prevention."
        "Choosing a career in tech is like taking an oath to lifelong growth."
        "How can you possibly have problems with your code? It literally does whatever you tell it."
        "You are the average of the five people you most associate with."
        "Some of your best stories will come from your worst days."
        "Behave as if the boss was watching, speak as if your mom was listening, work as if the new guy was watching, and do it all well because you are watching."
        "Your job is to help people. Whatever your position, this is your job."
        "Discovering you are wrong is a wonderful moment, not an awful one."
        "Never too old to ask questions. Never too strong to ask for help."
        "You made it this far. Celebrate your strength."
    )

    local idx=$((RANDOM % ${#thoughts[@]}))
    local thought="${thoughts[$idx]}"

    printf "\n  ${DIM}\"%s\"${NC}\n" "$thought"
    printf "  ${DIM}— Dave (author)${NC}\n\n"
}
